version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sms-citizen-create:1:1,sms-citizen-update:1:1,email-citizen-create:1:1,email-citizen-update:1:1"
    depends_on:
      - zookeeper

  kafka_consumer:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - kafka
      volumes:
        - .:/app
